version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: dine_outside
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  dev_postgres:
